version: '3.8'

services:
  backend:
    image: ghcr.io/chiranth-janardhan-moger/cloudpulse/backend:main-d2eaa00
    container_name: cloudpulse-backend
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
    restart: unless-stopped
    networks:
      - cloudpulse-network

  frontend:
    image: ghcr.io/chiranth-janardhan-moger/cloudpulse/frontend:main-d2eaa00
    container_name: cloudpulse-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - cloudpulse-network

networks:
  cloudpulse-network:
    driver: bridge
